"""add_verified_by_processor_column

Revision ID: f1f65fa53cc6
Revises: 781f00c76af7
Create Date: 2025-10-23 08:48:16.426802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1f65fa53cc6'
down_revision: Union[str, None] = '781f00c76af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faces', sa.Column('verified_by_processor', sa.String(length=100), nullable=True, comment="Recognition processor used (e.g., 'antelopev2', 'aws_rekognition')"))
    op.alter_column('faces', 'verified_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When photo was verified during recognition',
               existing_nullable=True)
    op.alter_column('faces', 'verified_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Recognition confidence score',
               existing_nullable=True)
    op.drop_index('ix_faces_new_provider_face_id', table_name='faces')
    op.drop_index('ix_faces_new_provider_face_id_provider', table_name='faces')
    op.drop_index('ix_faces_new_provider_name', table_name='faces')
    op.create_index(op.f('ix_faces_provider_face_id'), 'faces', ['provider_face_id'], unique=False)
    op.create_index('ix_faces_provider_face_id_provider', 'faces', ['provider_face_id', 'provider_name'], unique=True)
    op.create_index(op.f('ix_faces_provider_name'), 'faces', ['provider_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faces_provider_name'), table_name='faces')
    op.drop_index('ix_faces_provider_face_id_provider', table_name='faces')
    op.drop_index(op.f('ix_faces_provider_face_id'), table_name='faces')
    op.create_index('ix_faces_new_provider_name', 'faces', ['provider_name'], unique=False)
    op.create_index('ix_faces_new_provider_face_id_provider', 'faces', ['provider_face_id', 'provider_name'], unique=True)
    op.create_index('ix_faces_new_provider_face_id', 'faces', ['provider_face_id'], unique=False)
    op.alter_column('faces', 'verified_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Recognition confidence score',
               existing_nullable=True)
    op.alter_column('faces', 'verified_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When photo was verified during recognition',
               existing_nullable=True)
    op.drop_column('faces', 'verified_by_processor')
    # ### end Alembic commands ###
